export const PIECE_SIZE_MULTIPLIER = 0.75;
export const MOVING_SIZE_MULTIPLIER = 0.9;
export const TRANSITION_LENGTH_MILLISECONDS = 250;
export const BOT_PERFORM_ACTION_DELAY_MILLISECONDS = TRANSITION_LENGTH_MILLISECONDS * 2;
export type TAB_NAMES = "Standard" | "Advanced";
